//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningHour
    {
        public int Id { get; set; }
        public int PointOfSale { get; set; }
        public string Day { get; set; }
        public System.TimeSpan StartWork { get; set; }
        public System.TimeSpan EndWork { get; set; }
        public System.TimeSpan StartDinner { get; set; }
        public System.TimeSpan ExitDinner { get; set; }
    
        public virtual PointOfSale PointOfSale1 { get; set; }
    }
}
