//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleProduct
    {
        public int Product { get; set; }
        public int Sale { get; set; }
    
        public virtual Product Product1 { get; set; }
    }
}
