//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public System.DateTime Datetime { get; set; }
        public string PaymentType { get; set; }
        public string LoyaltyCard { get; set; }
    
        public virtual LoyaltyCard LoyaltyCard1 { get; set; }
    }
}
